apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb-deployment
  labels:
    app: helloweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloweb
  template:
    metadata:
      labels:
        app: helloweb
    spec:
      containers:
      - name: helloweb
        image: 885820436476.dkr.ecr.us-east-1.amazonaws.com/eks-cluster:${BUILD_NUMBER}
        ports:
        - containerPort: 3000
